### PR TITLE
Contact Photo available

### PR DESCRIPTION
**Pull request by joanpablo**
- Added the feature of get a contact's photo in full size or thumbnail mode. Tested in Android 5.0 and 7.1.1

### CODE REVIEW

**Comment by babariviere** [comment]
Hi @joanpablo, can you send me email? I would like to make you a proposal

**Comment by babariviere** [comment]
Hi,

Thanks but it's not that great for now, I think I have to rework some things.
And yes I will make you a maintainer of the package, as you seems pretty good and serious with testing!
And also thanks for your work!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by joanpablo** [comment]
Thanks to you Bastien. I have just started playing with Flutter, I like it
very much, and the first package I installed was 'flutter_sms'. The
community of Flutter is very small righ now but I belive it will grow this
2018 very much. Together we can make a really cool package.

**Comment by babariviere** [comment]
I think it too! That make me happy, thanks 😋

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request merged**
