### PR TITLE
feature/smsdb

### PR DESCRIPTION
**Pull request by ThinkDigitalRepair**

### CODE REVIEW

**Comment by ThinkDigitalRepair** [comment]
Includes the fix I mentioned earlier plus some additional code to get the feature working.

**Comment by babariviere** [comment]
Thanks for the pull request, can you please remove assert, log and required?

**Comment by ThinkDigitalRepair** [comment]
Sure

On Sep 20, 2018 10:54 PM, "Bastien Rivière" <notifications@github.com>
wrote:

Thanks for the pull request, can you please remove assert, log and required?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/babariviere/flutter_sms/pull/28#issuecomment-423421784>,
or mute the thread

**Comment by ThinkDigitalRepair** [comment]
The problem is that if it goes through without those values, it fails.

**Comment by babariviere** [comment]
Oh okay so you should let asserts but only remove required

**Comment by babariviere** [comment]
And maybe can you add a description for each assert? So the developer using this would find it more useful for debug

**Comment by ThinkDigitalRepair** [comment]
Right, ok. Explicit is better than implicit.

**Comment by babariviere** [comment]
Thanks you for this pull request 😁

**Comment by ThinkDigitalRepair** [comment]
Man, thank you for the library! I'll be submitting improvements for a while, hope you don't mind 😄

**Comment by ThinkDigitalRepair** [comment]
@babariviere what do you think about a new named constructor for `SmsMessage`?
Maybe something like `SmsMessage.valid()` or something (Name needs to change) to make on that's good for writing to the SmsDb? Cause I'd rather not see assertion failures and there's not an easy way to avoid errors before running. Just a small convenience.

**Comment by babariviere** [comment]
I have Facebook and discord if you want

**Comment by babariviere** [comment]
I don't think so but you can do it if you want

**Comment by babariviere** [comment]
We can also throw an error from insert function

**Comment by ThinkDigitalRepair** [comment]
You can find me at thinkdigital#6685 on Discord. I don't think the error is a good idea, because it may not show up until it's in production

**Comment by ThinkDigitalRepair** [comment]
I'm an advocate of showing errors as soon as possible.

**Comment by babariviere** [comment]
But the error can be catched at runtime

**Pull request merged**
